/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  ValidateNested,
  IsOptional,
  IsEnum,
  IsDate,
  IsInt,
  Max,
} from "class-validator";

import { MessageLogCreateNestedManyWithoutMessagesInput } from "./MessageLogCreateNestedManyWithoutMessagesInput";
import { Type } from "class-transformer";
import { EnumMessageMessageType } from "./EnumMessageMessageType";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { PracticeWhereUniqueInput } from "../../practice/base/PracticeWhereUniqueInput";
import { EnumMessageStatus } from "./EnumMessageStatus";

@InputType()
class MessageCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  content!: string;

  @ApiProperty({
    required: false,
    type: () => MessageLogCreateNestedManyWithoutMessagesInput,
  })
  @ValidateNested()
  @Type(() => MessageLogCreateNestedManyWithoutMessagesInput)
  @IsOptional()
  @Field(() => MessageLogCreateNestedManyWithoutMessagesInput, {
    nullable: true,
  })
  messageLog?: MessageLogCreateNestedManyWithoutMessagesInput;

  @ApiProperty({
    required: true,
    enum: EnumMessageMessageType,
  })
  @IsEnum(EnumMessageMessageType)
  @Field(() => EnumMessageMessageType)
  messageType!: "Instant" | "Delayed";

  @ApiProperty({
    required: true,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @Field(() => PatientWhereUniqueInput)
  patient!: PatientWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => PracticeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PracticeWhereUniqueInput)
  @Field(() => PracticeWhereUniqueInput)
  practice!: PracticeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  provider?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  providerId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  queueItemId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sentById?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  sentOn?: Date | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  smsCount!: number;

  @ApiProperty({
    required: false,
    enum: EnumMessageStatus,
  })
  @IsEnum(EnumMessageStatus)
  @IsOptional()
  @Field(() => EnumMessageStatus, {
    nullable: true,
  })
  status?: "Pending" | "Delivered" | "Failed" | null;
}

export { MessageCreateInput as MessageCreateInput };
