import { FeaturePermission } from "../featurePermission/FeaturePermission";
import { FormLink } from "../formLink/FormLink";
import { FormSubmission } from "../formSubmission/FormSubmission";
import { LeadFormLink } from "../leadFormLink/LeadFormLink";
import { Lead } from "../lead/Lead";
import { Patient } from "../patient/Patient";
import { PracticeInfoLink } from "../practiceInfoLink/PracticeInfoLink";
import { User } from "../user/User";
import { WorkflowTemplate } from "../workflowTemplate/WorkflowTemplate";

export type Practice = {
  addressLine1: string | null;
  addressLine2: string | null;
  addressLine3: string | null;
  createdAt: Date;
  featurePermission?: FeaturePermission | null;
  formLinks?: Array<FormLink>;
  formSubmissions?: Array<FormSubmission>;
  googlePlaceId: string | null;
  id: string;
  leadFormLinks?: Array<LeadFormLink>;
  leads?: Array<Lead>;
  name: string;
  nhsReviewUrl: string | null;
  odsCode: string;
  patients?: Array<Patient>;
  phoneNumber: string | null;
  postcode: string | null;
  practiceInfoLinks?: Array<PracticeInfoLink>;
  remindAfter: number;
  remindedAt: Date | null;
  remindEvery: number;
  sector?: "Dental" | "GP";
  senderId: string | null;
  stripeConnectedAccountId: string | null;
  updatedAt: Date;
  users?: Array<User>;
  website: string | null;
  workflowTemplates?: Array<WorkflowTemplate>;
};
