/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Link } from "./Link";
import { LinkCountArgs } from "./LinkCountArgs";
import { LinkFindManyArgs } from "./LinkFindManyArgs";
import { LinkFindUniqueArgs } from "./LinkFindUniqueArgs";
import { CreateLinkArgs } from "./CreateLinkArgs";
import { UpdateLinkArgs } from "./UpdateLinkArgs";
import { DeleteLinkArgs } from "./DeleteLinkArgs";
import { LinkService } from "../link.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Link)
export class LinkResolverBase {
  constructor(
    protected readonly service: LinkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Link",
    action: "read",
    possession: "any",
  })
  async _linksMeta(
    @graphql.Args() args: LinkCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Link])
  @nestAccessControl.UseRoles({
    resource: "Link",
    action: "read",
    possession: "any",
  })
  async links(@graphql.Args() args: LinkFindManyArgs): Promise<Link[]> {
    return this.service.links(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Link, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Link",
    action: "read",
    possession: "own",
  })
  async link(@graphql.Args() args: LinkFindUniqueArgs): Promise<Link | null> {
    const result = await this.service.link(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Link)
  @nestAccessControl.UseRoles({
    resource: "Link",
    action: "create",
    possession: "any",
  })
  async createLink(@graphql.Args() args: CreateLinkArgs): Promise<Link> {
    return await this.service.createLink({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Link)
  @nestAccessControl.UseRoles({
    resource: "Link",
    action: "update",
    possession: "any",
  })
  async updateLink(@graphql.Args() args: UpdateLinkArgs): Promise<Link | null> {
    try {
      return await this.service.updateLink({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Link)
  @nestAccessControl.UseRoles({
    resource: "Link",
    action: "delete",
    possession: "any",
  })
  async deleteLink(@graphql.Args() args: DeleteLinkArgs): Promise<Link | null> {
    try {
      return await this.service.deleteLink(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
