/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SubscriptionPlansStripeProductService } from "../subscriptionPlansStripeProduct.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SubscriptionPlansStripeProductCreateInput } from "./SubscriptionPlansStripeProductCreateInput";
import { SubscriptionPlansStripeProduct } from "./SubscriptionPlansStripeProduct";
import { SubscriptionPlansStripeProductFindManyArgs } from "./SubscriptionPlansStripeProductFindManyArgs";
import { SubscriptionPlansStripeProductWhereUniqueInput } from "./SubscriptionPlansStripeProductWhereUniqueInput";
import { SubscriptionPlansStripeProductUpdateInput } from "./SubscriptionPlansStripeProductUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SubscriptionPlansStripeProductControllerBase {
  constructor(
    protected readonly service: SubscriptionPlansStripeProductService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SubscriptionPlansStripeProduct })
  @nestAccessControl.UseRoles({
    resource: "SubscriptionPlansStripeProduct",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SubscriptionPlansStripeProductCreateInput,
  })
  async createSubscriptionPlansStripeProduct(
    @common.Body() data: SubscriptionPlansStripeProductCreateInput
  ): Promise<SubscriptionPlansStripeProduct> {
    return await this.service.createSubscriptionPlansStripeProduct({
      data: {
        ...data,

        subscriptionPlan: {
          connect: data.subscriptionPlan,
        },
      },
      select: {
        id: true,
        name: true,
        priceAmount: true,
        priceId: true,
        quantity: true,

        subscriptionPlan: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SubscriptionPlansStripeProduct] })
  @ApiNestedQuery(SubscriptionPlansStripeProductFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SubscriptionPlansStripeProduct",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async subscriptionPlansStripeProducts(
    @common.Req() request: Request
  ): Promise<SubscriptionPlansStripeProduct[]> {
    const args = plainToClass(
      SubscriptionPlansStripeProductFindManyArgs,
      request.query
    );
    return this.service.subscriptionPlansStripeProducts({
      ...args,
      select: {
        id: true,
        name: true,
        priceAmount: true,
        priceId: true,
        quantity: true,

        subscriptionPlan: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SubscriptionPlansStripeProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubscriptionPlansStripeProduct",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async subscriptionPlansStripeProduct(
    @common.Param() params: SubscriptionPlansStripeProductWhereUniqueInput
  ): Promise<SubscriptionPlansStripeProduct | null> {
    const result = await this.service.subscriptionPlansStripeProduct({
      where: params,
      select: {
        id: true,
        name: true,
        priceAmount: true,
        priceId: true,
        quantity: true,

        subscriptionPlan: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SubscriptionPlansStripeProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubscriptionPlansStripeProduct",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SubscriptionPlansStripeProductUpdateInput,
  })
  async updateSubscriptionPlansStripeProduct(
    @common.Param() params: SubscriptionPlansStripeProductWhereUniqueInput,
    @common.Body() data: SubscriptionPlansStripeProductUpdateInput
  ): Promise<SubscriptionPlansStripeProduct | null> {
    try {
      return await this.service.updateSubscriptionPlansStripeProduct({
        where: params,
        data: {
          ...data,

          subscriptionPlan: {
            connect: data.subscriptionPlan,
          },
        },
        select: {
          id: true,
          name: true,
          priceAmount: true,
          priceId: true,
          quantity: true,

          subscriptionPlan: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SubscriptionPlansStripeProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SubscriptionPlansStripeProduct",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSubscriptionPlansStripeProduct(
    @common.Param() params: SubscriptionPlansStripeProductWhereUniqueInput
  ): Promise<SubscriptionPlansStripeProduct | null> {
    try {
      return await this.service.deleteSubscriptionPlansStripeProduct({
        where: params,
        select: {
          id: true,
          name: true,
          priceAmount: true,
          priceId: true,
          quantity: true,

          subscriptionPlan: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
