/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HelpLinkService } from "../helpLink.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HelpLinkCreateInput } from "./HelpLinkCreateInput";
import { HelpLink } from "./HelpLink";
import { HelpLinkFindManyArgs } from "./HelpLinkFindManyArgs";
import { HelpLinkWhereUniqueInput } from "./HelpLinkWhereUniqueInput";
import { HelpLinkUpdateInput } from "./HelpLinkUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HelpLinkControllerBase {
  constructor(
    protected readonly service: HelpLinkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HelpLink })
  @nestAccessControl.UseRoles({
    resource: "HelpLink",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHelpLink(
    @common.Body() data: HelpLinkCreateInput
  ): Promise<HelpLink> {
    return await this.service.createHelpLink({
      data: data,
      select: {
        category: true,
        createdAt: true,
        displayName: true,
        id: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HelpLink] })
  @ApiNestedQuery(HelpLinkFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HelpLink",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async helpLinks(@common.Req() request: Request): Promise<HelpLink[]> {
    const args = plainToClass(HelpLinkFindManyArgs, request.query);
    return this.service.helpLinks({
      ...args,
      select: {
        category: true,
        createdAt: true,
        displayName: true,
        id: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HelpLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HelpLink",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async helpLink(
    @common.Param() params: HelpLinkWhereUniqueInput
  ): Promise<HelpLink | null> {
    const result = await this.service.helpLink({
      where: params,
      select: {
        category: true,
        createdAt: true,
        displayName: true,
        id: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HelpLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HelpLink",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHelpLink(
    @common.Param() params: HelpLinkWhereUniqueInput,
    @common.Body() data: HelpLinkUpdateInput
  ): Promise<HelpLink | null> {
    try {
      return await this.service.updateHelpLink({
        where: params,
        data: data,
        select: {
          category: true,
          createdAt: true,
          displayName: true,
          id: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HelpLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HelpLink",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHelpLink(
    @common.Param() params: HelpLinkWhereUniqueInput
  ): Promise<HelpLink | null> {
    try {
      return await this.service.deleteHelpLink({
        where: params,
        select: {
          category: true,
          createdAt: true,
          displayName: true,
          id: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
